# Secret Scanning Configuration
# https://docs.github.com/en/code-security/secret-scanning/using-advanced-secret-scanning-and-push-protection-features/excluding-folders-and-files-from-secret-scanning

paths-ignore:
  # Example/test files
  - "**/*.example"
  - "**/*.sample"
  - "**/examples/**"
  - "**/test/**"
  - "**/tests/**"
  
  # Documentation
  - "**/*.md"
  - "docs/**"
  
  # Environment examples (not actual secrets)
  - "**/.env.example"
  - "**/.env.sample"
  - "**/config/*.example.*"
  
  # Build artifacts
  - "**/dist/**"
  - "**/build/**"
  - "**/.next/**"
  
  # Node modules
  - "**/node_modules/**"
  
  # Keys directory (contains PGP public keys, not secrets)
  - "keys/*.asc"
